# SPDX-FileCopyrightText: 2021 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

env:
  SET_VERSION: "export TEZOS_VERSION=\"$(cat nix/nix/sources.json | jq -r '.tezos.ref' | cut -d'/' -f3)\""

steps:
 # We need to sign commits that update brew formulae separately
 - label: Sign formulae update commits
   if: build.branch =~ /^auto\/update-brew-formulae-.*/
   commands:
   - nix-shell ./scripts/shell.nix
       --run './scripts/sign-commits.sh'
 # To avoid race-conditions for the gpg key between jobs which sometimes leads to weird errors
 - wait

 - label: Install tezos-sapling-params-arm64
   key: install-tsp-arm64
   agents:
     queue: "arm64-darwin"
   commands:
   - brew install --formula ./Formula/tezos-sapling-params.rb

 - label: Build tezos-accuser-011-PtHangz2 bottle for Big Sur arm64
   key: build-bottle-1-arm64
   agents:
     queue: "arm64-darwin"
   commands:
   - ./scripts/build-one-bottle.sh "tezos-accuser-011-PtHangz2"
   artifact_paths:
     - '*.bottle.*'

 - label: Uninstall tezos-sapling-params arm64
   key: uninstall-tsp-arm64
   depends_on:
   - build-bottle-1-arm64
   agents:
     queue: "arm64-darwin"
   commands:
   - brew uninstall ./Formula/tezos-sapling-params.rb
   - brew autoremove

 # To avoid running two brew process together
 - wait

 - label: Install tezos-sapling-params-x86_64
   key: install-tsp-x86_64
   agents:
     queue: "x86_64-rosetta-darwin"
   commands:
   - brew install --formula ./Formula/tezos-sapling-params.rb

 - label: Build tezos-accuser-011-PtHangz2 bottle for Big Sur x86_64
   key: build-bottle-1-x86_64
   agents:
     queue: "x86_64-rosetta-darwin"
   commands:
   - ./scripts/build-one-bottle.sh "tezos-accuser-011-PtHangz2"
   artifact_paths:
     - '*.bottle.*'

 - label: Uninstall tezos-sapling-params x86_64
   key: uninstall-tsp-x86_64
   depends_on:
   - build-bottle-1-x86_64
   agents:
     queue: "x86_64-rosetta-darwin"
   commands:
   - brew uninstall ./Formula/tezos-sapling-params.rb
   - brew autoremove

 - label: reuse lint
   command: nix run -f . pkgs.reuse -c reuse lint
 - label: check trailing whitespace
   command: .buildkite/check-trailing-whitespace.sh
 - label: crossref-verify
   command: "nix run -f https://github.com/serokell/crossref-verifier/archive/68a1f9d25b6e7835fea8299b18a3e6c61dbb2a5c.tar.gz -c crossref-verify"
   soft_fail: true
 - label: lint python code
   command: nix run -f . pkgs.python39Packages.black -c black --check --diff --color .
 - label: pipeline-filtering
   command: nix-shell .buildkite/shell.nix --run 'nix run -f . pkgs.bats -c ./tests/buildkite/filter-pipeline.bats'
   only_changes:
   - .buildkite/filter-pipeline.py
   - tests/buildkite/.*
 - label: check auto-inserting bottle hashes
   commands:
   - cd tests/bottle-hashes/
   - ./test-hash-insert.sh

 - label: build via nix
   commands:
   - nix-build ./nix -A binaries -o binaries
   branches: "!master"
 - label: test nix-built binaries
   commands:
   - nix-build tests/tezos-nix-binaries.nix --no-out-link
   branches: "!master"
   # nix builds are usually cached, so we don't care about only_changes setting for it

 - label: build-via-docker
   # this step is used as a dependency, so we're defining 'key' explicitely
   key: build-via-docker
   commands:
   - eval "$SET_VERSION"
   - cd docker
   - ./docker-static-build.sh
   - nix run -f.. pkgs.upx -c upx tezos-*
   artifact_paths:
     - ./docker/tezos-*
   agents:
     queue: "docker"
   only_changes: &static_binaries_changes_regexes
   - docker/build/.*
   - docker/docker-static-build.sh
   - meta.json
   - protocols.json
   - nix/nix/sources.json
 # arm builer is an ubuntu machine without nix
 - label: build-arm-via-docker
   # this step is used as a dependency, so we're defining 'key' explicitely
   key: build-arm-via-docker
   commands:
   - eval "$SET_VERSION"
   - cd docker
   - ./docker-static-build.sh
   - upx tezos-*
   - >
     for f in ./tezos-*; do
       mv "\$f" "\$f-arm64"
     done
   artifact_paths:
     - ./docker/tezos-*
   agents:
     queue: "arm64-build"
   only_changes: *static_binaries_changes_regexes

 - label: test nixos modules
   commands:
   - nix-build tests/tezos-modules.nix --no-out-link

 - label: test docker-built binaries
   commands:
   - buildkite-agent artifact download "docker/*" . --step "build-via-docker"
   - chmod +x ./docker/*
   - nix-build tests/tezos-binaries.nix --no-out-link --arg path-to-binaries ./docker
   branches: "!master"
   depends_on:
    - "build-via-docker"
   only_changes:
   - tests/tezos-binaries.nix
   - tests/test_script.py
   # files from nix/ are massively used in tests ifrastructure
   - nix/.*

 - label: test deb source packages via docker
   commands:
   - eval "$SET_VERSION"
   - ./docker/docker-tezos-packages.sh --os ubuntu --type source
   artifact_paths:
     - ./out/*
   branches: "!master"
   timeout_in_minutes: 60
   agents:
     queue: "docker"
   only_changes: &native_packaging_changes_regexes
   - docker/package/.*
   - docker/docker-tezos-packages.sh
   - meta.json
   - protocols.json
   - nix/nix/sources.json
 - label: test deb binary packages via docker
   commands:
   - eval "$SET_VERSION"
   # Building all binary packages will take significant amount of time, so we build only one
   # in order to ensure package generation sanity
   - ./docker/docker-tezos-packages.sh --os ubuntu --type binary --package tezos-baker-011-PtHangz2
   - rm -rf out
   # It takes much time to build binary package, so we do it only on master
   branches: "master"
   timeout_in_minutes: 90
   agents:
     queue: "docker"
   only_changes: *native_packaging_changes_regexes
 - label: test rpm source packages via docker
   commands:
   - eval "$SET_VERSION"
   - ./docker/docker-tezos-packages.sh --os fedora --type source
   artifact_paths:
     - ./out/*
   branches: "!master"
   timeout_in_minutes: 60
   agents:
     queue: "docker"
   only_changes: *native_packaging_changes_regexes
 - label: test rpm binary packages via docker
   commands:
   - eval "$SET_VERSION"
   # Building all binary packages will take significant amount of time, so we build only one
   # in order to ensure package generation sanity
   - ./docker/docker-tezos-packages.sh --os fedora --type binary --package tezos-baker-011-PtHangz2
   - rm -rf out
   # It takes much time to build binary package, so we do it only on master
   branches: "master"
   timeout_in_minutes: 90
   agents:
     queue: "docker"
   only_changes: *native_packaging_changes_regexes

 - label: create auto release/pre-release
   key: auto-release
   commands:
   - mkdir binaries
   - mkdir arm-binaries
   - buildkite-agent artifact download "docker/*" binaries --step "build-via-docker"
   - buildkite-agent artifact download "docker/*" arm-binaries --step "build-arm-via-docker"
   - ls binaries
   - ./scripts/autorelease.sh "$BUILDKITE_MESSAGE"
   branches: master
   depends_on:
    - "build-via-docker"
    - "build-arm-via-docker"
   only_changes:
   - scripts/autorelease.sh
   - scripts/shell.nix
   # files from 'nix/' directory are used in the autorelease script
   - nix/.*
   - default.nix
   - release.nix

 # Update mirror repositories on master if brew formulae have been updated or bottle hashes added
 - label: update stable mirror repository
   if: |
     build.branch == "master" &&
       ( build.message =~ /^Merge pull request .* from serokell\/auto\/v[0-9]+\.[0-9]+-release/ ||
         build.message =~ /^Merge pull request .* from serokell\/auto\/update-brew-formulae-v[.0-9]+-[0-9]+/ )
   depends_on:
   - "auto-release"
   env:
    MIRROR_REPO: "git@github.com:serokell/tezos-packaging-stable.git"
   commands: &update_mirror
   - git pull origin "$BUILDKITE_BRANCH:$BUILDKITE_BRANCH"
   - git push --mirror "$MIRROR_REPO"

 - label: update RC mirror repository
   if: |
     build.branch == "master" &&
       (build.message =~ /^Merge pull request .* from serokell\/auto\/v[0-9]+\.[0-9]+-rc.*-release/ ||
          build.message =~ /^Merge pull request .* from serokell\/auto\/update-brew-formulae-v[.0-9]+-rc.*/)
   depends_on:
   - "auto-release"
   env:
    MIRROR_REPO: "git@github.com:serokell/tezos-packaging-rc.git"
   commands: *update_mirror
