# SPDX-FileCopyrightText: 2021 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

env:
  SET_VERSION: "export OCTEZ_VERSION=\"$(cat meta.json | jq -r '.tezos_ref' | cut -d'/' -f3)\""
  USE_NEWER_NIX: 1

steps:
 # We need to sign commits that update brew formulae separately
 - label: Sign formulae update commits
   if: build.branch =~ /^auto\/update-brew-formulae-.*/
   commands:
   - nix develop .#buildkite
       --command './scripts/sign-commits.sh'
 # To avoid race-conditions for the gpg key between jobs which sometimes leads to weird errors
 - wait

 - label: reuse lint
   command: nix shell .#reuse -c reuse lint
 - label: check trailing whitespace
   command: .buildkite/check-trailing-whitespace.sh
 - label: crossref-verify
   command: nix shell -f https://github.com/serokell/crossref-verifier/archive/68a1f9d25b6e7835fea8299b18a3e6c61dbb2a5c.tar.gz -c crossref-verify
   soft_fail: true
 - label: lint python code
   command: nix shell .#python39Packages.black -c black --check --diff --color .
 - label: lint bash scripts
   command: nix shell .#shellcheck -c shellcheck --shell=bash --exclude=SC1091 -x $(find . -name '*.sh')
 - label: pipeline-filtering
   command: nix develop .#buildkite --command 'nix shell .#bats -c ./tests/buildkite/filter-pipeline.bats'
   only_changes:
   - .buildkite/filter-pipeline.py
   - tests/buildkite/.*
 - label: check auto-inserting bottle hashes
   commands:
   - cd tests/bottle-hashes/
   - ./test-hash-insert.sh

 - label: Build Big Sur x86_64 bottles
   key: build-bottles-big-sur-x86_64
   branches: "pasqu4le/v15-test"
   agents:
     queue: "x86_64-rosetta-darwin"
   commands:
   - nix develop .#autorelease-macos -c ./scripts/build-all-bottles.sh "big_sur"
   artifact_paths:
     - '*.bottle.*'
   retry:
     automatic:
       limit: 1

 # To avoid running two brew processes together
 - wait

 - label: Build Big Sur arm64 bottles
   key: build-bottles-big-sur-arm64
   branches: "pasqu4le/v15-test"
   agents:
     queue: "arm64-darwin"
   commands:
   - nix develop .#autorelease-macos -c ./scripts/build-all-bottles.sh "arm64_big_sur"
   artifact_paths:
     - '*.bottle.*'
   retry:
     automatic:
       limit: 1
