# SPDX-FileCopyrightText: 2021 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

env:
  SET_VERSION: "export OCTEZ_VERSION=\"$(cat meta.json | jq -r '.tezos_ref' | cut -d'/' -f3)\""
  USE_NEWER_NIX: 1

steps:
 - label: Build source packages
   key: build-source-packages
   branches: "pasqu4le/tmp-2"
   agents:
     queue: "docker"
   commands:
   - eval "$SET_VERSION"
   - ./docker/docker-tezos-packages.sh --os ubuntu --type source
   - ./docker/docker-tezos-packages.sh --os fedora --type source
   artifact_paths:
     - ./out/*

 - label: Publish native packages
   branches: "pasqu4le/tmp-2"
   depends_on:
   - "build-source-packages"
   commands:
   - eval "$SET_VERSION"
   - buildkite-agent artifact download "out/*" . --step build-source-packages
   - nix develop .#autorelease -c ./scripts/publish-native-packages.sh out
