# SPDX-FileCopyrightText: 2022 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

env:
  USE_NEWER_NIX: 1
  SET_VERSION: "export OCTEZ_VERSION=\"$(cat meta.json | jq -r '.tezos_ref' | cut -d'/' -f3)\""


steps:
 - label: Check for new Octez release
   if: build.source == "schedule" && build.branch == "master"
   commands:
   - nix develop .#autorelease -c ./scripts/update-tezos.sh

 - label: Build source packages
   key: build-source-packages
   if: build.tag =~ /^v.*-1/
   agents:
     queue: "docker"
   commands:
   - eval "$SET_VERSION"
   - ./docker/docker-tezos-packages.sh --os ubuntu --type source
   - ./docker/docker-tezos-packages.sh --os fedora --type source
   artifact_paths:
     - ./out/*

 - label: Publish native packages
   if: build.tag =~ /^v.*-1/
   depends_on:
   - "build-source-packages"
   commands:
   - eval "$SET_VERSION"
   - buildkite-agent artifact download "out/*" . --step build-source-packages
   - ./scripts/publish-native-packages.sh out

 - label: Build Big Sur x86_64 bottles
   key: build-bottles-big-sur-x86_64
   if: build.tag =~ /^v.*/
   agents:
     queue: "x86_64-rosetta-darwin"
   commands:
   - nix develop .#autorelease-macos -c ./scripts/build-all-bottles.sh "big_sur"
   artifact_paths:
     - '*.bottle.*'
   retry:
     automatic:
       limit: 1

 # To avoid running two brew processes together
 - wait

 - label: Build Big Sur arm64 bottles
   key: build-bottles-big-sur-arm64
   if: build.tag =~ /^v.*/
   agents:
     queue: "arm64-darwin"
   commands:
   - nix develop .#autorelease-macos -c ./scripts/build-all-bottles.sh "arm64_big_sur"
   artifact_paths:
     - '*.bottle.*'
   retry:
     automatic:
       limit: 1

 # We use the tag that triggered the pipeline here. Normally, this isn't very resilient,
 # but in 'scripts/sync-bottle-hashes.sh' it's only used for informational purposes
 - label: Add Big Sur bottle hashes to formulae
   depends_on:
   - "build-bottles-big-sur-arm64"
   - "build-bottles-big-sur-x86_64"
   if: build.tag =~ /^v.*/
   soft_fail: true # No artifacts to download if all the bottles are already built
   commands:
   - mkdir -p "Big Sur"
   - buildkite-agent artifact download "*bottle.tar.gz" "Big Sur/"
   - nix develop .#autorelease -c ./scripts/sync-bottle-hashes.sh "$BUILDKITE_TAG" "Big Sur"
