#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2022 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

set -euo pipefail

# $PROTOCOL should be defined in the system unit environment
node="/usr/bin/tezos-tx-rollup-node-$PROTOCOL"
tezos_client="/usr/bin/tezos-client"

"$node" init "$MODE" config \
    for "$ROLLUP_ALIAS" \
    --data-dir "$DATA_DIR" \
    --rpc-addr "$ROLLUP_NODE_RPC_ENDPOINT" \
    --force

# Waiting till node start to respond
while ! "$tezos_client" --endpoint "$NODE_RPC_ENDPOINT" rpc list &> /dev/null; do sleep 1; done

"$node" --endpoint "$NODE_RPC_ENDPOINT" \
    run "$ROLLUP_MODE" for "$ROLLUP_ALIAS" \
    --data-dir "$DATA_DIR" &
