name: Build homebrew bottles
on: push
permissions:
  # Restrict GITHUB_TOKEN permissions
  contents: write
jobs:
  build-bottles:
    runs-on: ${{ matrix.os.id }}

    strategy:
      fail-fast: false
      matrix:
        os: [ { id: macos-10.15, name: "catalina" }, { id: macos-11, name: "big_sur" } ]
        # we don't bottle meta-formulas that contain only services
        formula: [tezos-accuser-011-PtHangz2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: check-built
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        name: Check if the bottle has already been built
        continue-on-error: true
        run: gh release view v11.1-1 | grep "${{ matrix.formula }}.*${{ matrix.os.name }}.bottle.tar.gz"

      - name: Install coreutils for macOS # for sha256sum
        if: steps.check-built.outcome == 'failure'
        run: brew install coreutils

      - name: Install GNU sed # for the other pipeline compatibility
        if: steps.check-built.outcome == 'failure'
        run: |
          brew install gnu-sed
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH

        # tezos-sapling-params is used as a dependency for some of the formulas
        # so we handle it separately.
        # We don't build the bottle for it because it is never updated over time.
      - name: Build tezos-sapling-params
        if: steps.check-built.outcome == 'failure'
        run: brew install --formula ./Formula/tezos-sapling-params.rb

      - name: Build the bottle
        if: steps.check-built.outcome == 'failure'
        run: ./scripts/build-one-bottle.sh "${{ matrix.formula }}"

      - name: Upload the bottle to Github Actions
        if: steps.check-built.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: homebrew-bottles-${{ matrix.os }}
          path: '*.bottle.*'

  sync-hashes:
    runs-on: macos-10.15
    needs: build-bottles
    steps:
       # It's possible we have had to rerun the building workflow, skipping some jobs and
       # erasing the previously built bottles, so we use the release to download them all
      - name: Download Catalina bottles from the release
        run: exit 0 # just checking if 'needs' works
